name: Update ts playground link

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup node.js env
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Restore dependencies
      run: cd tools/prepare-ts-playground && npm i
    - name: Update README.md
      run: npm start
    - id: git_commit
      uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: Update README.md
        author_name: github action