name: Update ts playground link

on:
  push:
    branches: [ main, expr ]
  pull_request:

concurrency:
  group: prepare-link-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup node.js env
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Restore dependencies
      run: cd tools/prepare-ts-playground && npm i

    - name: Update docs' ts-playground links
      run: cd tools/prepare-ts-playground && npm run toc && npm run doc

    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update ts-playground links for docs